openapi: '3.0.0'
info:
  version: 1.0.0
  title: api-ping-rl
  description: |-
    Standard definitions for commonly used ping endpoint.
    APIs should import this API fragment to ensure standard consistency.
    The root main file of the API must include this "paths" on it.
paths:
  /ping:
    get:
      description: This is an endpoint to check for availability of API
      operationId: ping
      parameters:
        #- $ref: 'api-headers-rl.yaml#/components/parameters/xCorrelationId'
        - in: query
          name: mode
          required: false
          schema:
            type: string
            enum: [verbose]         
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: 'api-ping-rl.yaml#/components/schemas/PingResponse'
              examples:
                PingResponse:
                  $ref: 'api-ping-rl.yaml#/components/examples/SuccessPingResponse'
                PingResponseVerbose:
                  $ref: 'api-ping-rl.yaml#/components/examples/SuccessPingResponseVerbose'
components:
  schemas:
    PingResponse:
      type: object
      required:
        - appName
        - appVersion
        - appStatus
        - timestamp
      properties:
        appName: 
          type: string
          example: 'layer-api'
        appVersion:
          type: string
          example: '1.0.0'
        appStatus:
          type: string
          example: 'RUNNING'
        timestamp:
          type: string
          format: date-time
          example: '2021-03-16T11:17:21.167Z'
        appProperties:
          type: object
          properties:
            deployedAppName:
              type: string
            muleVersion:
              type: string
            encoding:
              type: string
            standalone:
              type: boolean
            workDir:
              type: string
            listeningHost:
              type: string 
        reservedProperties:
          type: object
          properties:
            javaVendor:
              type: string
            javaName:
              type: string
            javaVersion:
              type: string
            orgId:
              type: string
            envId:
              type: string
            envType:
              type: string
            workerId:
              type: string 
            domain:
              type: string 
            fullDomain:
              type: string 
            region:
              type: string 
            httpPort:
              type: string 
            httpPrivatePort:
              type: string 
            httpsPrivatePort:
              type: string 
            muleHome:
              type: string
        serverProperties:
          type: object
          properties:
            time:
              type: string
            host:
              type: string
            ipAddr:
              type: string
            javaVendor:
              type: string
            osArch:
              type: string
            osName:
              type: string
            osVersion:
              type: string 
            fileSeparator:
              type: string 
            tmpDir:
              type: string 
            userDir:
              type: string 
            userHome:
              type: string 
            userName:
              type: string
  examples:
    SuccessPingResponse:
      value:
        appName: 'sapi-workitem-rl'
        appVersion: '1.0.0'
        appStatus: 'RUNNING'
        timestamp: '2021-03-16T11:17:21.167Z'
    SuccessPingResponseVerbose:
      value:
        appName: 'sapi-workitem-rl'
        appVersion: '1.0.0'
        appStatus: 'RUNNING'
        timestamp: '2021-03-16T11:17:21.167Z'
        appProperties:
          deployedAppName: 'sapi-workitem-rl'
          muleVersion: '4.3.0-20210427'
          encoding: 'UTF-8'
          standalone: true
          workDir: 'C:\\dev\\AnypointStudio-7.9.0-win64\\AnypointStudio\\plugins\\org.mule.tooling.server.4.3.0.ee_7.3.5.202105101830\\mule/./.mule/sapi-workitem-rl'
          listeningHost: 'localhost:8092'
        reservedProperties:
          javaVendor: 'AdoptOpenJDK'
          javaName: 'OpenJDK Runtime Environment'
          javaVersion: '1.8.0_282'
          orgId: 'null'
          envId: 'null'
          envType: 'null'
          workerId: 'null'
          domain: 'null'
          fullDomain: 'null'
          region: 'null'
          httpPort: 'null'
          httpsPort: 'null'
          httpPrivatePort: 'null'
          httpsPrivatePort: 'null'
          muleHome: 'C:\\dev\\AnypointStudio-7.9.0-win64\\AnypointStudio\\plugins\\org.mule.tooling.server.4.3.0.ee_7.3.5.202105101830\\mule'
        serverProperties:
          time: '2021-05-14T11:21:59.554+0200'
          host: 'directoryserver.ca.local'
          ipAddr: '192.168.33.1'
          javaVendor: 'AdoptOpenJDK'
          javaVersion: '1.8.0_282'
          osArch: 'amd64'
          osName: 'Windows 10'
          osVersion: '10.0'
          fileSeparator: '\\'
          tmpDir: 'C:\\Users\\fperezgo\\AppData\\Local\\Temp\\'
          userDir: 'C:\\dev\\AnypointStudio-7.9.0-win64\\AnypointStudio\\plugins\\org.mule.tooling.server.4.3.0.ee_7.3.5.202105101830\\mule\\bin'
          userHome: 'C:\\Users\\fperezgo'
          userName: 'fperezgo'